# Generated by Django 5.2.1 on 2025-07-13 15:53

import core.validators.phone_validator
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('education', models.CharField(choices=[('general', 'General'), ('specialist', 'Specialist'), ('sub_specialist', 'Sub_Specialist'), ('fellowship', 'Fellowship')], default='general', max_length=30)),
                ('lisence', models.PositiveIntegerField()),
                ('biography', models.TextField()),
                ('achive', models.CharField(blank=True, max_length=128, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='core.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('notapproved', 'NotApproved')], default='notapproved', max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_comment', to='core.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_comment', to='core.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=11, validators=[core.validators.phone_validator.validate_phone_number])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clincs', to='core.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
